services:
  php-apache:
    build:
      target: php-apache
      context: .
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
    links:
      - mysql
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: p6-tomtroc
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  persistent: